# -*- coding: utf-8 -*-
"""PD Survey Analysis (Slice by Experience Score) From SF Data - Updated 2021-12-16.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1-7J7fvD8PpjsKf1h1iZCqy2wLS8fZzY9

***Dependencies and Data***
"""

# Importing packages
import csv
import numpy as np
import pandas as pd
import os
import glob
import matplotlib.pyplot as plt
from collections import Counter
from statistics import mean
from re import search

# Dependencies
# Set working directory
path = '/Users/juanpena/Dropbox/My Mac (Juan’s MacBook Pro (2))/Documents/Python/PD_Survey/2021 DEN C4 - PD Survey/2021 DEN C4 - Python Reports'
os.chdir(path)
 
# https://docs.google.com/spreadsheets/d/1AX-1drRL7mrnar4QOfDqcL9f5pxxB2ErD4txn8Hv6yU/edit#gid=275520015
# download / save file as excel
filename = '2021 DEN C4 End of PD Survey - Week 6 (Responses) - Python Data.xlsx'

# callout for specific tab & create dataframe
tab_name = 'Python Data Prepared'
raw_data_df = pd.read_excel(filename, sheet_name = tab_name)

raw_data_df.columns

# Dropdown Options: 1) Very Poor, 2) Poor, 3) Acceptable, 4) Good, 5) Very Good
def tran_very_poor_very_good(x):
    if x == 'Very Poor':
        return 1
    if x == 'Poor':
        return 2
    if x == 'Acceptable':
        return 3
    if x == 'Good':
        return 4
    if x == 'Very Good':
        return 5

# Dropdown Options: 1) Not at all, 2) A little bit, 3) Fairly, 4) Very, 5) Extremely
def tran_notatall_extremely(x):
    if search('Not at all', x):
        return 1
    if search('A little bit', x):
        return 2
    if search('Fairly', x):
        return 3
    if search('Very', x):
        return 4
    if search('Extremely', x):
        return 5

# Dropdown Options: 1) Not at all, 2) Slightly, 3) Fairly, 4) Very, 5) Extremely
def tran_notatall_extremely1(x):
    if search('Not at all', x):
        return 1
    if search('Slightly', x):
        return 2
    if search('Fairly', x):
        return 3
    if search('Very', x):
        return 4
    if search('Extremely', x):
        return 5

# Dropdown Options: 1) Much less than, 2) Less than, 3) Somewhat, 4) Exceeded, 5) Greatly exceeded
def tran_muchless_greatly(x):
    if search('Much less than', x):
        return 1
    if search('Less than', x):
        return 2
    if search('Somewhat', x):
        return 3
    if search('Exceeded', x):
        return 4
    if search('Greatly exceeded', x):
        return 5

raw_data_df['experience_overall_trans'] = raw_data_df['experience_overall'].apply(tran_very_poor_very_good)
raw_data_df['pd_emotional_safety_trans'] = raw_data_df['pd_emotional_safety'].apply(tran_notatall_extremely)
raw_data_df['program_expectations_trans'] = raw_data_df['program_expectations'].apply(tran_muchless_greatly)
raw_data_df['expectations_recruitment_trans'] = raw_data_df['expectations_recruitment'].apply(tran_notatall_extremely1)
raw_data_df['program_support_trans'] = raw_data_df['program_support'].apply(tran_notatall_extremely)
raw_data_df['connected_coach_trans'] = raw_data_df['connected_coach'].apply(tran_notatall_extremely)
raw_data_df['connected_staff_trans'] = raw_data_df['connected_staff'].apply(tran_notatall_extremely)
raw_data_df['connected_other_leaders_trans'] = raw_data_df['connected_other_leaders'].apply(tran_notatall_extremely)
raw_data_df['coach_helpfulness_trans'] = raw_data_df['coach_helpfulness'].apply(tran_notatall_extremely)
raw_data_df['value_family_gathering_trans'] = raw_data_df['value_family_gathering'].apply(tran_notatall_extremely)
raw_data_df['enjoy_family_gathering_trans'] = raw_data_df['enjoy_family_gathering'].apply(tran_notatall_extremely)
raw_data_df['connected_allies_trans'] = raw_data_df['connected_allies'].apply(tran_notatall_extremely)
raw_data_df['experience_small_group_trans'] = raw_data_df['experience_small_group'].apply(tran_very_poor_very_good)
raw_data_df['support_small_group_trans'] = raw_data_df['support_small_group'].apply(tran_notatall_extremely)

raw_data_df.columns

numeric_data_only_df = raw_data_df[['experience_overall_trans', 'pd_emotional_safety_trans', 
                                    'program_expectations_trans', 'expectations_recruitment_trans', 
                                    'program_support_trans', 'connected_coach_trans', 'connected_staff_trans', 
                                    'connected_other_leaders_trans', 'coach_helpfulness_trans', 
                                    'value_family_gathering_trans', 'enjoy_family_gathering_trans', 
                                    'connected_allies_trans', 'experience_small_group_trans', 
                                    'support_small_group_trans'
                                   ]]
numeric_data_only_df.head()

frequencies = {}
for i in numeric_data_only_df.columns:
    frequencies[i] = numeric_data_only_df[i].value_counts()

frequencies_numeric_data = pd.DataFrame(frequencies)
frequencies_numeric_data_rename = frequencies_numeric_data.rename(columns={'experience_overall_trans': 'How would you rate your overall experience with CrossPurpose?',
                                                                           'pd_emotional_safety_trans': 'Did you feel emotionally safe in the classroom environment?',
                                                                           'program_expectations_trans': 'Did Personal Development meet your expectations?',
                                                                           'expectations_recruitment_trans': 'Was the program characterized correctly during the recruitment and interview process?',
                                                                           'program_support_trans': 'How supported did you feel during Personal Development?',
                                                                           'connected_coach_trans': 'How connected do you feel to your Coach?',
                                                                           'connected_staff_trans': 'How connected do you feel to other staff at CrossPurpose?',
                                                                           'connected_other_leaders_trans': 'How connected do you feel to other Leaders at CrossPurpose?',
                                                                           'coach_helpfulness_trans': 'How helpful has coaching been during Personal Development?',
                                                                           'value_family_gathering_trans': 'How valuable (useful or important) has the Family Gathering experience been for you so far?',
                                                                           'enjoy_family_gathering_trans': 'How enjoyable (delightful) are Family Gatherings for you?',
                                                                           'connected_allies_trans': 'How connected do you feel to Allies at CrossPurpose so far?',
                                                                           'experience_small_group_trans': 'How would you rate your experience with your small group so far?',
                                                                           'support_small_group_trans': 'How supported do you feel by your small group?',
                                                                          })
frequencies_numeric_data_rename

plotdata = frequencies_numeric_data_rename.transpose()
plotdata.head()

plotdata2 = plotdata.div(plotdata.sum(axis=1), axis=0)*100
plotdata2.head()

plotdata2.plot(kind='barh', stacked=True, color=['red', 'orange', 'blue', 'green'])
plt.legend(bbox_to_anchor=(1.05,1))
plt.title('PD 2020 C4 Exit Survey Analysis')
plt.ylabel('Survey Questions')
plt.xlabel('Cumulative Percent')
plt.show()

experience_overall_pd_5_df = raw_data_df.loc[raw_data_df['experience_overall_trans'] == 5]
experience_overall_pd_less_5_df = raw_data_df.loc[raw_data_df['experience_overall_trans'] < 5]
experience_overall_pd_less_5_df

numeric_experience_overall_pd_5_df = experience_overall_pd_5_df[['experience_overall_trans', 
                                                                 'pd_emotional_safety_trans',
                                                                 'program_expectations_trans', 
                                                                 'expectations_recruitment_trans',
                                                                 'program_support_trans', 
                                                                 'connected_coach_trans', 
                                                                 'connected_staff_trans', 
                                                                 'connected_other_leaders_trans', 
                                                                 'coach_helpfulness_trans',
                                                                 'value_family_gathering_trans', 
                                                                 'enjoy_family_gathering_trans',
                                                                 'connected_allies_trans', 
                                                                 'experience_small_group_trans', 
                                                                 'support_small_group_trans'
                                                                ]]
numeric_experience_overall_pd_5_df.head(1)

numeric_experience_overall_pd_less_5_df = experience_overall_pd_less_5_df[['experience_overall_trans',
                                                                           'pd_emotional_safety_trans',
                                                                           'program_expectations_trans', 
                                                                           'expectations_recruitment_trans',
                                                                           'program_support_trans', 
                                                                           'connected_coach_trans',
                                                                           'connected_staff_trans',
                                                                           'connected_other_leaders_trans',
                                                                           'coach_helpfulness_trans',
                                                                           'value_family_gathering_trans', 
                                                                           'enjoy_family_gathering_trans',
                                                                           'connected_allies_trans',
                                                                           'experience_small_group_trans', 
                                                                           'support_small_group_trans'
                                                                          ]]
numeric_experience_overall_pd_less_5_df.head(1)

mean_numeric_data_only_df = numeric_data_only_df.mean().round(1)
mean_experience_overall_5 = numeric_experience_overall_pd_5_df.mean().round(1)
mean_experience_overall_less_5 = numeric_experience_overall_pd_less_5_df.mean().round(1)

# Combine two Pandas dataframes with the same index
mean_df = pd.concat([mean_numeric_data_only_df, mean_experience_overall_5, mean_experience_overall_less_5 ], axis=1)

mean_df_rename = mean_df.rename(columns={0: 'Avg. Score (Overall)', 1: 'Avg. Score (PD Experience = 5)', 
                                         2: 'Avg. Score (PD Experience < 5)'}, inplace=True)

mean_df.head(1)

def letter_grade(x):
    if x >= 4.5:
        letter = 'A'
    elif x >= 4:
        letter = 'B'
    elif x >= 3.5:
        letter = 'C'
    elif x >= 3:
        letter = 'D'
    else:
        letter = 'F'
    return letter

mean_df['Avg. Score (Overall) Grade'] = mean_df['Avg. Score (Overall)'].apply(letter_grade)
mean_df['Avg. Score (PD Experience = 5) Grade'] = mean_df['Avg. Score (PD Experience = 5)'].apply(letter_grade)
mean_df['Avg. Score (PD Experience < 5) Grade'] = mean_df['Avg. Score (PD Experience < 5)'].apply(letter_grade)
mean_df

# save dataframe to excel
mean_df.to_excel('/Users/juanpena/Dropbox/My Mac (Juan’s MacBook Pro (2))/Documents/Python/PD_Survey/2021 DEN C4 - PD Survey/2021 DEN C4 - Python Reports/PD_Survey_Report_Card.xls')

"""***Overall Experience***"""

overall_experience_why_5 = (experience_overall_pd_5_df[['leader_file_name', 'experience_overall', 
                                                          'overall_experience_why']]
                                  .rename(columns={'leader_file_name': 'Leader Name', 
                                                   'experience_overall': 'How would you rate your overall experience with CrossPurpose?',
                                                   'overall_experience_why': 'Why did you rate your overall experience this way?'}))
overall_experience_why_less_5 = (experience_overall_pd_less_5_df[['leader_file_name', 'experience_overall', 
                                                          'overall_experience_why']]
                                  .rename(columns={'leader_file_name': 'Leader Name', 
                                                   'experience_overall': 'How would you rate your overall experience with CrossPurpose?',
                                                   'overall_experience_why': 'Why did you rate your overall experience this way?'}))

overall_experience_why_less_5.head()

# save dataframe to excel
overall_experience_why_5.to_excel('/Users/juanpena/Dropbox/My Mac (Juan’s MacBook Pro (2))/Documents/Python/PD_Survey/2021 DEN C4 - PD Survey/2021 DEN C4 - Python Reports/overall_experience_why_5.xls')
overall_experience_why_less_5.to_excel('/Users/juanpena/Dropbox/My Mac (Juan’s MacBook Pro (2))/Documents/Python/PD_Survey/2021 DEN C4 - PD Survey/2021 DEN C4 - Python Reports/overall_experience_why_less_5.xls')

"""***Most Impactful Classes***"""

# https://stackoverflow.com/questions/20894525/how-to-remove-parentheses-and-all-data-within-using-pandas-python
pd_most_impactful_classes_df = raw_data_df['pd_most_impactful_classes'].str.replace(r" \(.*\)","")
pd_most_impactful_classes = pd_most_impactful_classes_df.str.get_dummies(sep=', ')
pd_most_impactful_classes_agg = (pd_most_impactful_classes.agg(['mean', 'sum'])
                              .round(1).sort_values(by = 'sum', axis = 1))

# save dataframe to excel
pd_most_impactful_classes_agg.to_excel('/Users/juanpena/Dropbox/My Mac (Juan’s MacBook Pro (2))/Documents/Python/PD_Survey/2021 DEN C4 - PD Survey/2021 DEN C4 - Python Reports/most_impactful_classes_agg.xls')

pd_most_impactful_classes_why_5 = (experience_overall_pd_5_df[['leader_file_name', 'pd_most_impactful_classes', 
                                                          'pd_most_impactful_classes_why']]
                                      .rename(columns={'leader_file_name': 'Leader Name', 
                                                        'pd_most_impactful_classes': 'Which 2 types of classes were MOST impactful for you? (Choose ONLY 2)', 
                                                        'pd_most_impactful_classes_why': 'Why were these two types of classes MOST impactful for you?'}))

pd_most_impactful_classes_why_less_5 = (experience_overall_pd_less_5_df[['leader_file_name', 'pd_most_impactful_classes', 
                                                          'pd_most_impactful_classes_why']]
                                      .rename(columns={'leader_file_name': 'Leader Name', 
                                                        'pd_most_impactful_classes': 'Which 2 types of classes were MOST impactful for you? (Choose ONLY 2)', 
                                                        'pd_most_impactful_classes_why': 'Why were these two types of classes MOST impactful for you?'}))

pd_most_impactful_classes_why_5.head(1)

# save dataframe to excel
pd_most_impactful_classes_why_5.to_excel('/Users/juanpena/Dropbox/My Mac (Juan’s MacBook Pro (2))/Documents/Python/PD_Survey/2021 DEN C4 - PD Survey/2021 DEN C4 - Python Reports/most_impactful_classes_why_5.xls')
pd_most_impactful_classes_why_less_5.to_excel('/Users/juanpena/Dropbox/My Mac (Juan’s MacBook Pro (2))/Documents/Python/PD_Survey/2021 DEN C4 - PD Survey/2021 DEN C4 - Python Reports/most_impactful_classes_why_less_5.xls')

"""***Least Impactful Classes***"""

# https://stackoverflow.com/questions/20894525/how-to-remove-parentheses-and-all-data-within-using-pandas-python
pd_least_impactful_classes_df = raw_data_df['pd_least_impactful_classes'].str.replace(r" \(.*\)","")
pd_least_impactful_classes = pd_least_impactful_classes_df.str.get_dummies(sep=', ')
pd_least_impactful_classes_agg = (pd_least_impactful_classes.agg(['mean', 'sum'])
                               .round(1).sort_values(by = 'sum', axis = 1))
pd_least_impactful_classes_agg

# save dataframe to excel
pd_least_impactful_classes_agg.to_excel('/Users/juanpena/Dropbox/My Mac (Juan’s MacBook Pro (2))/Documents/Python/PD_Survey/2021 DEN C4 - PD Survey/2021 DEN C4 - Python Reports/least_impactful_classes_agg.xls')

pd_least_impactful_classes_why_5 = (experience_overall_pd_5_df[['leader_file_name', 'pd_least_impactful_classes', 
                                                          'pd_least_impactful_classes_why']]
                                       .rename(columns={'leader_file_name': 'Leader Name', 
                                                        'pd_least_impactful_classes': 'Which 2 types of classes were LEAST impactful for you? (Choose ONLY 2)', 
                                                        'pd_least_impactful_classes_why': 'Why were these two types of classes LEAST impactful for you?'}))

pd_least_impactful_classes_why_less_5 = (experience_overall_pd_less_5_df[['leader_file_name', 'pd_least_impactful_classes', 
                                                          'pd_least_impactful_classes_why']]
                                       .rename(columns={'leader_file_name': 'Leader Name', 
                                                        'pd_least_impactful_classes': 'Which 2 types of classes were LEAST impactful for you? (Choose ONLY 2)', 
                                                        'pd_least_impactful_classes_why': 'Why were these two types of classes LEAST impactful for you?'}))

# least_impactful_classes_why_above_9

# save dataframe to excel
pd_least_impactful_classes_why_5.to_excel('/Users/juanpena/Dropbox/My Mac (Juan’s MacBook Pro (2))/Documents/Python/PD_Survey/2021 DEN C4 - PD Survey/2021 DEN C4 - Python Reports/least_impactful_classes_why_5.xls')
pd_least_impactful_classes_why_less_5.to_excel('/Users/juanpena/Dropbox/My Mac (Juan’s MacBook Pro (2))/Documents/Python/PD_Survey/2021 DEN C4 - PD Survey/2021 DEN C4 - Python Reports/least_impactful_classes_why_less_5.xls')

"""***Add A Topic To PD***"""

pd_add_topic_5 = (experience_overall_pd_5_df[['leader_file_name', 'pd_add_topic']]
                       .rename(columns={'leader_file_name': 'Leader Name', 
                                       'pd_add_topic': 'If we could add one topic to discuss in class, what would it be and why?'}))
pd_add_topic_less_5 = (experience_overall_pd_less_5_df[['leader_file_name', 'pd_add_topic']]
                       .rename(columns={'leader_file_name': 'Leader Name', 
                                       'pd_add_topic': 'If we could add one topic to discuss in class, what would it be and why?'}))

# pd_add_topic_above_9

# save dataframe to excel
pd_add_topic_5.to_excel('/Users/juanpena/Dropbox/My Mac (Juan’s MacBook Pro (2))/Documents/Python/PD_Survey/2021 DEN C4 - PD Survey/2021 DEN C4 - Python Reports/add_a_topic_5.xls')
pd_add_topic_less_5.to_excel('/Users/juanpena/Dropbox/My Mac (Juan’s MacBook Pro (2))/Documents/Python/PD_Survey/2021 DEN C4 - PD Survey/2021 DEN C4 - Python Reports/add_a_topic_less_5.xls')

"""***Emotional Safety***"""

pd_emotional_safety_why_5 = (experience_overall_pd_5_df[['leader_file_name', 'pd_emotional_safety', 
                                                          'pd_emotional_safety_why']]
                                .rename(columns={'leader_file_name': 'Leader Name', 
                                                 'pd_emotional_safety': 'Did you feel emotionally safe in the classroom environment?', 
                                                 'pd_emotional_safety_why': 'Why did you rate your overall emotional safety this way?'}))
pd_emotional_safety_why_less_5 = (experience_overall_pd_less_5_df[['leader_file_name', 'pd_emotional_safety', 
                                                          'pd_emotional_safety_why']]
                                .rename(columns={'leader_file_name': 'Leader Name', 
                                                 'pd_emotional_safety': 'Did you feel emotionally safe in the classroom environment?', 
                                                 'pd_emotional_safety_why': 'Why did you rate your overall emotional safety this way?'}))

# pd_emotional_safety_why_why_less_5

# save dataframe to excel
pd_emotional_safety_why_5.to_excel('/Users/juanpena/Dropbox/My Mac (Juan’s MacBook Pro (2))/Documents/Python/PD_Survey/2021 DEN C4 - PD Survey/2021 DEN C4 - Python Reports/emotional_safety_why_5.xls')
pd_emotional_safety_why_less_5.to_excel('/Users/juanpena/Dropbox/My Mac (Juan’s MacBook Pro (2))/Documents/Python/PD_Survey/2021 DEN C4 - PD Survey/2021 DEN C4 - Python Reports/emotional_safety_why_less_5.xls')

"""***Most Difficult Part Of PD***"""

pd_difficult_part_5 = (experience_overall_pd_5_df[['leader_file_name', 'pd_difficult_part']]
                          .rename(columns={'leader_file_name': 'Leader Name', 
                                           'pd_difficult_part': 'What was the most difficult part of Personal Development?'}))
pd_difficult_part_less_5 = (experience_overall_pd_less_5_df[['leader_file_name', 'pd_difficult_part']]
                          .rename(columns={'leader_file_name': 'Leader Name', 
                                           'pd_difficult_part': 'What was the most difficult part of Personal Development?'}))

# pd_difficult_part_5

# save dataframe to excel
pd_difficult_part_5.to_excel('/Users/juanpena/Dropbox/My Mac (Juan’s MacBook Pro (2))/Documents/Python/PD_Survey/2021 DEN C4 - PD Survey/2021 DEN C4 - Python Reports/difficult_part_5.xls')
pd_difficult_part_less_5.to_excel('/Users/juanpena/Dropbox/My Mac (Juan’s MacBook Pro (2))/Documents/Python/PD_Survey/2021 DEN C4 - PD Survey/2021 DEN C4 - Python Reports/difficult_part_less_5.xls')

"""***Best Part Of PD***"""

pd_best_part_5 = (experience_overall_pd_5_df[['leader_file_name', 'pd_best_part']]
                     .rename(columns={'leader_file_name': 'Leader Name', 
                                           'pd_best_part': 'What was the best part of Personal Development?'}))
pd_best_part_less_5 = (experience_overall_pd_less_5_df[['leader_file_name', 'pd_best_part']]
                     .rename(columns={'leader_file_name': 'Leader Name', 
                                           'pd_best_part': 'What was the best part of Personal Development?'}))

# pd_best_part_5

# save dataframe to excel
pd_best_part_5.to_excel('/Users/juanpena/Dropbox/My Mac (Juan’s MacBook Pro (2))/Documents/Python/PD_Survey/2021 DEN C4 - PD Survey/2021 DEN C4 - Python Reports/best_part_5.xls')
pd_best_part_less_5.to_excel('/Users/juanpena/Dropbox/My Mac (Juan’s MacBook Pro (2))/Documents/Python/PD_Survey/2021 DEN C4 - PD Survey/2021 DEN C4 - Python Reports/best_part_less_5.xls')

"""***PD Expectations***"""

program_expectations_5 = (experience_overall_pd_5_df[['leader_file_name', 'program_expectations', 'program_expectations_what']]
                          .rename(columns={'leader_file_name': 'Leader Name', 
                                           'program_expectations': 'Did Personal Development meet your expectations?', 
                                           'program_expectations_what': 'What expectations were/weren’t met?'}))
program_expectations_less_5 = (experience_overall_pd_less_5_df[['leader_file_name', 'program_expectations', 'program_expectations_what']]
                           .rename(columns={'leader_file_name': 'Leader Name', 
                                           'program_expectations': 'Did Personal Development meet your expectations?', 
                                           'program_expectations_what': 'What expectations were/weren’t met?'}))

# program_expectations_less_5

# save dataframe to excel
program_expectations_5.to_excel('/Users/juanpena/Dropbox/My Mac (Juan’s MacBook Pro (2))/Documents/Python/PD_Survey/2021 DEN C4 - PD Survey/2021 DEN C4 - Python Reports/pd_expectations_5.xls')
program_expectations_less_5.to_excel('/Users/juanpena/Dropbox/My Mac (Juan’s MacBook Pro (2))/Documents/Python/PD_Survey/2021 DEN C4 - PD Survey/2021 DEN C4 - Python Reports/pd_expectations_less_5.xls')

"""***Recruitment Expectations***"""

expectations_recruitment_5 = (experience_overall_pd_5_df[['leader_file_name', 'expectations_recruitment', 
                                                            'expectations_recruitment_what']]
                                    .rename(columns={'leader_file_name': 'Leader Name', 
                                                     'expectations_recruitment': 'Was the program characterized correctly during the recruitment and interview process?', 
                                                     'expectations_recruitment_what': 'What could be communicated better?'}))
expectations_recruitment_less_5 = (experience_overall_pd_less_5_df[['leader_file_name', 'expectations_recruitment', 
                                                            'expectations_recruitment_what']]
                                    .rename(columns={'leader_file_name': 'Leader Name', 
                                                     'expectations_recruitment': 'Was the program characterized correctly during the recruitment and interview process?', 
                                                     'expectations_recruitment_what': 'What could be communicated better?'}))

# expectations_recruitment_5

# save dataframe to excel
expectations_recruitment_5.to_excel('/Users/juanpena/Dropbox/My Mac (Juan’s MacBook Pro (2))/Documents/Python/PD_Survey/2021 DEN C4 - PD Survey/2021 DEN C4 - Python Reports/recruitment_expectations_5.xls')
expectations_recruitment_less_5.to_excel('/Users/juanpena/Dropbox/My Mac (Juan’s MacBook Pro (2))/Documents/Python/PD_Survey/2021 DEN C4 - PD Survey/2021 DEN C4 - Python Reports/recruitment_expectations_less_5.xls')

"""***Support During PD***"""

program_support_5 = (experience_overall_pd_5_df[['leader_file_name', 'program_support']]
                      .rename(columns={'leader_file_name': 'Leader Name', 
                                       'program_support': 'How supported did you feel during Personal Development?'}))
program_support_less_5 = (experience_overall_pd_less_5_df[['leader_file_name', 'program_support']]
                      .rename(columns={'leader_file_name': 'Leader Name', 
                                       'program_support': 'How supported did you feel during Personal Development?'}))

# program_support_5

# save dataframe to excel
program_support_5.to_excel('/Users/juanpena/Dropbox/My Mac (Juan’s MacBook Pro (2))/Documents/Python/PD_Survey/2021 DEN C4 - PD Survey/2021 DEN C4 - Python Reports/support_pd_5.xls')
program_support_less_5.to_excel('/Users/juanpena/Dropbox/My Mac (Juan’s MacBook Pro (2))/Documents/Python/PD_Survey/2021 DEN C4 - PD Survey/2021 DEN C4 - Python Reports/support_pd_less_5.xls')

"""***Coaching Questions***"""

coaching_5 = (experience_overall_pd_5_df[['leader_file_name', 'connected_coach', 'coach_helpfulness', 
                                           'coach_most_beneficial', 'coach_support_better_what']]
                    .rename(columns={'leader_file_name': 'Leader Name', 
                                     'connected_coach': 'How connected do you feel to your Coach?', 
                                     'coach_helpfulness': 'How helpful has coaching been during Personal Development?', 
                                     'coach_most_beneficial': 'What has been the most beneficial element of coaching for you?', 
                                     'coach_support_better_what': 'What is one way your coach could better support you?'}))
coaching_less_5 = (experience_overall_pd_less_5_df[['leader_file_name', 'connected_coach', 'coach_helpfulness', 
                                           'coach_most_beneficial', 'coach_support_better_what']]
                    .rename(columns={'leader_file_name': 'Leader Name', 
                                     'connected_coach': 'How connected do you feel to your Coach?', 
                                     'coach_helpfulness': 'How helpful has coaching been during Personal Development?', 
                                     'coach_most_beneficial': 'What has been the most beneficial element of coaching for you?', 
                                     'coach_support_better_what': 'What is one way your coach could better support you?'}))

# coaching_5

# save dataframe to excel
coaching_5.to_excel('/Users/juanpena/Dropbox/My Mac (Juan’s MacBook Pro (2))/Documents/Python/PD_Survey/2021 DEN C4 - PD Survey/2021 DEN C4 - Python Reports/coaching_5.xls')
coaching_less_5.to_excel('/Users/juanpena/Dropbox/My Mac (Juan’s MacBook Pro (2))/Documents/Python/PD_Survey/2021 DEN C4 - PD Survey/2021 DEN C4 - Python Reports/coaching_less_5.xls')

"""***Connected Questions***"""

connected_pd_5 = (experience_overall_pd_5_df[['leader_file_name', 'connected_coach', 'connected_staff', 
                                               'connected_other_leaders', 'connected_allies']]
                        .rename(columns={'leader_file_name': 'Leader Name', 
                                         'connected_coach': 'How connected do you feel to your Coach?', 
                                         'connected_staff': 'How connected do you feel to other staff at CrossPurpose?', 
                                         'connected_other_leaders': 'How connected do you feel to other Leaders at CrossPurpose?', 
                                         'connected_allies': 'How connected do you feel to Allies at CrossPurpose so far?'}))
connected_pd_less_5 = (experience_overall_pd_less_5_df[['leader_file_name', 'connected_coach', 'connected_staff', 
                                               'connected_other_leaders', 'connected_allies']]
                        .rename(columns={'leader_file_name': 'Leader Name', 
                                         'connected_coach': 'How connected do you feel to your Coach?', 
                                         'connected_staff': 'How connected do you feel to other staff at CrossPurpose?', 
                                         'connected_other_leaders': 'How connected do you feel to other Leaders at CrossPurpose?', 
                                         'connected_allies': 'How connected do you feel to Allies at CrossPurpose so far?'}))

# connected_pd_5

# save dataframe to excel
connected_pd_5.to_excel('/Users/juanpena/Dropbox/My Mac (Juan’s MacBook Pro (2))/Documents/Python/PD_Survey/2021 DEN C4 - PD Survey/2021 DEN C4 - Python Reports/connected_pd_5.xls')
connected_pd_less_5.to_excel('/Users/juanpena/Dropbox/My Mac (Juan’s MacBook Pro (2))/Documents/Python/PD_Survey/2021 DEN C4 - PD Survey/2021 DEN C4 - Python Reports/connected_pd_less_5.xls')

"""***How To Improve PD***"""

improve_pd_5 = (experience_overall_pd_5_df[['leader_file_name', 'program_improvement']]
                      .rename(columns={'leader_file_name': 'Leader Name', 
                                       'program_improvement': 'If you could do one thing to improve Personal Development, what would it be?'}))
improve_pd_less_5 = (experience_overall_pd_less_5_df[['leader_file_name', 'program_improvement']]
                      .rename(columns={'leader_file_name': 'Leader Name', 
                                       'program_improvement': 'If you could do one thing to improve Personal Development, what would it be?'}))

# improve_pd_5

# save dataframe to excel
improve_pd_5.to_excel('/Users/juanpena/Dropbox/My Mac (Juan’s MacBook Pro (2))/Documents/Python/PD_Survey/2021 DEN C4 - PD Survey/2021 DEN C4 - Python Reports/improve_pd_5.xls')
improve_pd_less_5.to_excel('/Users/juanpena/Dropbox/My Mac (Juan’s MacBook Pro (2))/Documents/Python/PD_Survey/2021 DEN C4 - PD Survey/2021 DEN C4 - Python Reports/improve_pd_less_5.xls')

"""***Learned About Self***"""

learn_about_self_5 = (experience_overall_pd_5_df[['leader_file_name', 'learn_about_self']]
                               .rename(columns={'leader_file_name': 'Leader Name', 
                                       'learn_about_self': 'What did you learn about yourself? How did you grow?'}))
learn_about_self_less_5 = (experience_overall_pd_less_5_df[['leader_file_name', 'learn_about_self']]
                               .rename(columns={'leader_file_name': 'Leader Name', 
                                       'learn_about_self': 'What did you learn about yourself? How did you grow?'}))

# learn_about_self_5

# save dataframe to excel
learn_about_self_5.to_excel('/Users/juanpena/Dropbox/My Mac (Juan’s MacBook Pro (2))/Documents/Python/PD_Survey/2021 DEN C4 - PD Survey/2021 DEN C4 - Python Reports/learn_about_self_pd_5.xls')
learn_about_self_less_5.to_excel('/Users/juanpena/Dropbox/My Mac (Juan’s MacBook Pro (2))/Documents/Python/PD_Survey/2021 DEN C4 - PD Survey/2021 DEN C4 - Python Reports/learn_about_self_pd_less_5.xls')

"""***Family Gathering Questions***"""

fg_questions_5 = (experience_overall_pd_5_df[['leader_file_name', 'value_family_gathering', 
                                                 'value_family_gathering_why', 'enjoy_family_gathering',
                                                'family_gathering_change']]
                        .rename(columns={'leader_file_name': 'Leader Name', 
                                         'value_family_gathering': 'How valuable (useful or important) has the Family Gathering experience been for you so far?', 
                                         'value_family_gathering_why': 'Why did you rate the value of Family Gathering to you this way?', 
                                         'enjoy_family_gathering': 'How enjoyable (delightful) are Family Gatherings for you?', 
                                         'family_gathering_change': 'If you could change one thing about the Family Gathering experience, what would you change?'}))
fg_questions_less_5 = (experience_overall_pd_less_5_df[['leader_file_name', 'value_family_gathering', 
                                                 'value_family_gathering_why', 'enjoy_family_gathering',
                                                'family_gathering_change']]
                        .rename(columns={'leader_file_name': 'Leader Name', 
                                         'value_family_gathering': 'How valuable (useful or important) has the Family Gathering experience been for you so far?', 
                                         'value_family_gathering_why': 'Why did you rate the value of Family Gathering to you this way?', 
                                         'enjoy_family_gathering': 'How enjoyable (delightful) are Family Gatherings for you?', 
                                         'family_gathering_change': 'If you could change one thing about the Family Gathering experience, what would you change?'}))

# fg_questions_5

# save dataframe to excel
fg_questions_5.to_excel('/Users/juanpena/Dropbox/My Mac (Juan’s MacBook Pro (2))/Documents/Python/PD_Survey/2021 DEN C4 - PD Survey/2021 DEN C4 - Python Reports/fg_questions_5.xls')
fg_questions_less_5.to_excel('/Users/juanpena/Dropbox/My Mac (Juan’s MacBook Pro (2))/Documents/Python/PD_Survey/2021 DEN C4 - PD Survey/2021 DEN C4 - Python Reports/fg_questions_less_5.xls')

"""***Small Group Questions***"""

sg_questions_5 = (experience_overall_pd_5_df[['leader_file_name', 'experience_small_group', 
                                                'support_small_group', 'small_group_beneficial', 
                                                'small_group_change']]
                        .rename(columns={'leader_file_name': 'Leader Name', 
                                         'experience_small_group': 'How would you rate your experience with your small group so far?', 
                                         'support_small_group': 'How supported do you feel by your small group?', 
                                         'small_group_beneficial': 'What has been the most beneficial element of small groups for you?', 
                                         'small_group_change': 'If you could change one thing about your small group experience, what would you change?'}))
sg_questions_less_5 = (experience_overall_pd_less_5_df[['leader_file_name', 'experience_small_group', 
                                                'support_small_group', 'small_group_beneficial', 
                                                'small_group_change']]
                        .rename(columns={'leader_file_name': 'Leader Name', 
                                         'experience_small_group': 'How would you rate your experience with your small group so far?', 
                                         'support_small_group': 'How supported do you feel by your small group?', 
                                         'small_group_beneficial': 'What has been the most beneficial element of small groups for you?', 
                                         'small_group_change': 'If you could change one thing about your small group experience, what would you change?'}))

# sg_questions_5

# save dataframe to excel
sg_questions_5.to_excel('/Users/juanpena/Dropbox/My Mac (Juan’s MacBook Pro (2))/Documents/Python/PD_Survey/2021 DEN C4 - PD Survey/2021 DEN C4 - Python Reports/sg_questions_5.xls')
sg_questions_less_5.to_excel('/Users/juanpena/Dropbox/My Mac (Juan’s MacBook Pro (2))/Documents/Python/PD_Survey/2021 DEN C4 - PD Survey/2021 DEN C4 - Python Reports/sg_questions_less_5.xls')

"""***Final Comments***"""

final_comments_5 = (experience_overall_pd_5_df[['leader_file_name', 'experience_final_comments']]
                          .rename(columns={'leader_file_name': 'Leader Name', 
                                           'experience_final_comments': 'Is there anything else you would like us to know about your experience as a Leader in CrossPurpose?'}))
final_comments_less_5 = (experience_overall_pd_less_5_df[['leader_file_name', 'experience_final_comments']]
                          .rename(columns={'leader_file_name': 'Leader Name', 
                                           'experience_final_comments': 'Is there anything else you would like us to know about your experience as a Leader in CrossPurpose?'}))

# final_comments_5

# save dataframe to excel
final_comments_5.to_excel('/Users/juanpena/Dropbox/My Mac (Juan’s MacBook Pro (2))/Documents/Python/PD_Survey/2021 DEN C4 - PD Survey/2021 DEN C4 - Python Reports/final_comments_5.xls')
final_comments_less_5.to_excel('/Users/juanpena/Dropbox/My Mac (Juan’s MacBook Pro (2))/Documents/Python/PD_Survey/2021 DEN C4 - PD Survey/2021 DEN C4 - Python Reports/final_comments_less_5.xls')



